name = "remix-cloudflare-workers"
workers_dev = true

# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-09-14"
compatibility_flags = ["streams_enable_constructors"]

main = "worker/index.ts"

[site]
  bucket = "./public"

[define]
  "process.env.REMIX_DEV_SERVER_WS_PORT" = "8002"

[vars]
  ENCRYPTION_KEY="foobar"
