name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: shopify-ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          CI=true npm i
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
